baseURL: 'https://ibrunotome.github.io'
title: Bruno Tomé
theme: hugo-notepadium
copyright: ©2020 Bruno Tomé.
languageCode: pt
defaultContentLanguage: pt
hasCJKLanguage: true
enableRobotsTXT: true
disqusShortname: ibrunotome
googleAnalytics: UA-40327355-1

languages:
  pt:
    contentDir: content/pt
    languageName: Portuguese
    weight: 10
  en:
    contentDir: content/en
    languageName: Inglês
    weight: 20

markup:
  highlight:
    codeFences: true
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

params:
  style: dark
  dateFormat: 02 Jan, 2006
  readingTime: true
  logo: ''
  slogan: ''
  license: ''
  fullRss: false
  comments:
    enable: true
  math:
    enable: false
    use: katex
  syntax:
    use: none
    theme: xcode
    darkTheme: xcode-dark
  share:
    enable: false
    addThisId: ''
    inlineToolId: ''
  nav:
    showCategories: true
    showTags: true
    custom:
      - title: Sobre
        url: /about
  beian:
    icp: ''
    gongan: ''
    code: ''

permalinks:
  posts: "/:title"
